name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/kakaxi-1/IPTV.git || true
          git fetch upstream

      - name: Merge upstream changes
        run: |
          # 尝试合并
          if ! git merge upstream/main --allow-unrelated-histories; then
            # 如果合并失败，使用上游版本
            git checkout --theirs epg.xml
            git add epg.xml
            git commit -m "Resolve merge conflict: using upstream version of epg.xml"
          else
            git add .
            git commit -m "Sync with upstream" || echo "No changes to commit"
          fi

      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 